version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install aws-sam-cli
      - pip install -r src/handlers/crud_plantilla/requirements.txt
      - pip install -r src/handlers/crud_tipo_plantilla/requirements.txt
      # - pip install -r src/handlers/health/requirements.txt
  build:
    commands:
      - sam build --config-file samconfig.toml

  post_build:
    commands:
      - sam package --config-file samconfig.toml --output-template-file packaged.yaml
      # Desplegar el proyecto SAM
      - sam deploy --config-file samconfig.toml --no-confirm-changeset

artifacts:
  files:
    - packaged.yaml
