version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install aws-sam-cli
      - pip install -r hello_world/requirements.txt
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --s3-bucket your-s3-bucket-name --output-template-file packaged.yaml
      - sam deploy --template-file packaged.yaml --stack-name my-sam-app --capabilities CAPABILITY_IAM
