AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'A simple AWS Lambda function using SAM'
Resources:
  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello_world/app.lambda_handler
      Runtime: python3.8
      CodeUri: hello_world/
      Description: 'A simple Hello World Lambda function'
      MemorySize: 128
      Timeout: 3
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          PARAM1: 'value'
